fix(acl): configmap was hardcoded in the sts
vernemq/docker-vernemq pull request #357
Opened 2023-07-06 11:51 UTC by eyenx

Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>

2023-07-06 12:07 UTC, ioolkos commented
@eyenx ok, makes sense to me, thanks!

2023-07-06 17:40 UTC, ioolkos requested changes
`::` is a typo? can you update

2023-07-17 07:17 UTC, eyenx commented on helm/vernemq/templates/statefulset.yaml
> +            name:: {{ include "vernemq.fullname" . }}-acl
```suggestion
            name: {{ include "vernemq.fullname" . }}-acl
```

2023-07-17 07:17 UTC, eyenx commented
> `::` is a typo? can you update

Done. Thanks.

2023-08-28 18:11 UTC, ioolkos approved these changes

2023-08-28 18:11 UTC, merged